configMapGenerator:
- files:
  - application.yml
  name: 82265683-configmap
  namesapce: "82265683"
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepgstapacr.azurecr.io/82265683
  newTag: "202410170602"
- name: cepgstapacr.azurecr.io/cloud-sample
  newTag: "202410160836"
